### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by leayz-888** [triple-Mu/YOLO-TensorRT8#11]
您好，当我使用您提供的命令进行将yolov7.pt转化为onnx过程中报错：
Traceback (most recent call last):
  File "./export.py", line 146, in <module>
    main(opt)
  File "./export.py", line 85, in main
    model_onnx, check = onnxsim.simplify(model_onnx)
  File "/home/cidi/.local/lib/python3.6/site-packages/onnxsim/onnx_simplifier.py", line 587, in simplify
    model = fixed_point(model, constant_folding, infer_shapes_and_optimize)
  File "/home/cidi/.local/lib/python3.6/site-packages/onnxsim/onnx_simplifier.py", line 474, in fixed_point
    x = func_a(x)
  File "/home/cidi/.local/lib/python3.6/site-packages/onnxsim/onnx_simplifier.py", line 581, in constant_folding
    custom_lib=custom_lib)
  File "/home/cidi/.local/lib/python3.6/site-packages/onnxsim/onnx_simplifier.py", line 307, in forward_for_node_outputs
    custom_lib=custom_lib)
  File "/home/cidi/.local/lib/python3.6/site-packages/onnxsim/onnx_simplifier.py", line 260, in forward
    ), sess_options=sess_options, providers=['CPUExecutionProvider'])
  File "/home/cidi/.local/lib/python3.6/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 335, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/cidi/.local/lib/python3.6/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 370, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_bytes, False, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Fatal error: EfficientNMS_TRT is not a registered function/op
请问这是哪里出问题了呢？

**Comment by triple-Mu** [comment]
您可以执行以下语句看看吗？
``` python3
import onnxsim
print(onnxsim.__version__)
```
如果是 0.4.1 以下的版本目前还不支持 需要您升级到 0.4.1 以上
``` shell
python3 -m pip install onnxsim --upgrade
```

**Comment by leayz-888** [comment]
> 



> 

成功了，大佬牛逼！请问还可以请教您一个问题吗？

**Comment by triple-Mu** [comment]
> > 
> 
> > 
> 
> 成功了，大佬牛逼！请问还可以请教您一个问题吗？

我是个臭弟弟 :laughing:
什么问题可以帮您看看

**Comment by leayz-888** [comment]
> > > 
> > 
> > 
> > > 
> > 
> > 
> > 成功了，大佬牛逼！请问还可以请教您一个问题吗？
> 
> 我是个臭弟弟 laughing 什么问题可以帮您看看

哈哈，大佬太谦虚了，
是这样的：我将官方提供的yolov7.pt转yolov7.onnx，然后再转trt，trt推理的结果和pt模型推理的结果基本一致；
然后我用yolov7训练了一个自己的模型，也转成了trt，但是发现trt的推理结果比pt模型的推理结果差了好多，不知道是为啥，能加个联系方式咨询一下么？嘻嘻（vx:15705425632）

**Comment by triple-Mu** [comment]
> 

YOLOv7 貌似自定义数据集训练的 conf score 很低. 不过我没自己训练转过，目前还不清楚什么情况

**Comment by leayz-888** [comment]
> > 
> 
> YOLOv7 貌似自定义数据集训练的 conf score 很低. 不过我没自己训练转过，目前还不清楚什么情况

Yolov7给出的模型配置文件有个deploy，还有个training，不知道这两个有什么区别，我训练的时候是用training中的yolov7.yaml配置文件训练的

**Comment by triple-Mu** [comment]
> > > 
> > 
> > 
> > YOLOv7 貌似自定义数据集训练的 conf score 很低. 不过我没自己训练转过，目前还不清楚什么情况
> 
> Yolov7给出的模型配置文件有个deploy，还有个training，不知道这两个有什么区别，我训练的时候是用training中的yolov7.yaml配置文件训练的

我加你vx没通过。我的是 18811050244
